# Note: This recipe currently only works on OS X and Linux. Furthermore, on OS
# X, it is built with --without-x (terminal emacs only). Feel free to lift
# either of these restrictions if you are able to get it to build.

{% set version = "26.1" %}

package:
  name: emacs
  version: {{ version }}

source:
  fn: emacs-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
  sha256: 1cf4fc240cd77c25309d15e18593789c8dbfba5c2b44d8f77c886542300fd32c

build:
  number: 1  # [not linux]
  number: 2  # [linux]
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - giflib
    - gnutls
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - zlib

  run:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - giflib
    - gnutls
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - zlib

test:
  commands:
    - $PREFIX/bin/emacs --help
    - $PREFIX/bin/emacsclient --help
    - $PREFIX/bin/ctags --help
    - $PREFIX/bin/ebrowse --help
    - $PREFIX/bin/etags --help
    - $PREFIX/bin/emacs -nw -Q --kill --batch

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0
  summary: 'GNU Emacs is an extensible, customizable text editor.'
  license_file: COPYING

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - notestaff
