# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "b3SDvcDd6Bi3WvGmg6tkWMyQ9/tunQRhwSA5O4aiZygSFH8elyT6LEsn88AX6QeAn54t2S1OVk5aCGtWbZN7O6rZeZETDBbWeIYOQc4rJGJ6f99YTxROQ+/WhoYwOvzPLkXGssYXGADac0LObJh365CY05STG2lon/xaqjydaBQSGF3WeRiqNkkM830ZTAd8ugArxzAP2KWQNyUbmTSOH9agcVb5530MPcfnWL2tRyxEQpQhogXIiz4Ap14YYaIO7RnuMiEezgZ3pv+l+IOFPQhQXqW+w4Na7YjDTlxqSBIak7PTlF+wDuVIbNwpuUudDGwXuz0UUQI8i8dr6MmzihOe1fXxDtqSyym7eMLRJ9KWj64eRzPxat9MyzK7GHQI1OpaEu4Tu6vs9GmA4f96f0kAkiaLRyw0EF/qgjiQdQWRndWRT0IaaVR4omwcUDNJNZQH/gXutI8Q5uxU9N/bLKINL2ZAXVf5sLORgpovidkrqWb3Ooo54e8o+zdvssprLcsH/7PH+u1d6NqlPU6vOBhWpSs+CNYP9yxDc6Brd7lG0GQlotzUNL5zPlskaT3jftt0oq2dRljFZ0JF7MkINAMUudY73AoeQXBt08NJNrv4syn+y4RYf0v5MqEPJc1LL4rY8NsxVSmiiWE2TcC5NfPLEr2pGYACCx7oNIwa+tg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  #################################################
  #              BEGIN CUSTOM CHANGE              #
  #                                               #
  # This change needs to stay intact on rerenders #
  #################################################

  # The build contains hardcoded references to the work directory in the
  # binary files. To fix this, we make the work directory exactly as long as
  # the placeholder prefix (255 characters).

  # The prefix ends with '/work/emacs-25.1' (16 characters). We put it in the
  #  miniconda3 directory, '/Users/travis/miniconda3/' (25 characters), so our
  # placeholder directory name needs 214 characters.

  - export CONDA_BLD_PATH=/Users/travis/miniconda3/placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
  # We also need to set --no-build-id to avoid the recipe_1481871472196
  # subdirectory.
  - conda build --no-build-id ./recipe

  #################################################
  #              END CUSTOM CHANGE                #
  #################################################

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
