travis:
  secure:
    BINSTAR_TOKEN: b3SDvcDd6Bi3WvGmg6tkWMyQ9/tunQRhwSA5O4aiZygSFH8elyT6LEsn88AX6QeAn54t2S1OVk5aCGtWbZN7O6rZeZETDBbWeIYOQc4rJGJ6f99YTxROQ+/WhoYwOvzPLkXGssYXGADac0LObJh365CY05STG2lon/xaqjydaBQSGF3WeRiqNkkM830ZTAd8ugArxzAP2KWQNyUbmTSOH9agcVb5530MPcfnWL2tRyxEQpQhogXIiz4Ap14YYaIO7RnuMiEezgZ3pv+l+IOFPQhQXqW+w4Na7YjDTlxqSBIak7PTlF+wDuVIbNwpuUudDGwXuz0UUQI8i8dr6MmzihOe1fXxDtqSyym7eMLRJ9KWj64eRzPxat9MyzK7GHQI1OpaEu4Tu6vs9GmA4f96f0kAkiaLRyw0EF/qgjiQdQWRndWRT0IaaVR4omwcUDNJNZQH/gXutI8Q5uxU9N/bLKINL2ZAXVf5sLORgpovidkrqWb3Ooo54e8o+zdvssprLcsH/7PH+u1d6NqlPU6vOBhWpSs+CNYP9yxDc6Brd7lG0GQlotzUNL5zPlskaT3jftt0oq2dRljFZ0JF7MkINAMUudY73AoeQXBt08NJNrv4syn+y4RYf0v5MqEPJc1LL4rY8NsxVSmiiWE2TcC5NfPLEr2pGYACCx7oNIwa+tg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
