compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  # Azure doesn't allow disabling address space randomization. This can be
  # removed for emacs 27.
  linux: circle
  osx: azure
conda_forge_output_validation: true
